#@TYPE: Machine
#@NAME: CompuLab ucm-imx95 Evaluation Kit
#@SOC: i.MX95
#@DESCRIPTION: Machine configuration for CompuLab ucm-imx95 EVK
#@MAINTAINER: compulab@compulab.co.il

require compulab-imx95.inc

KERNEL_DEVICETREE:append = " \
    compulab/ucm-imx95-som.dtb \
    compulab/ucm-imx95.dtb \
    compulab/ucm-imx95-rpmsg.dtb \
    compulab/ucm-imx95-evk-csi1-ap1302.dtb \
    compulab/ucm-imx95-evk-csi2-ap1302.dtb \
"

UBOOT_DTB_NAME = "ucm-imx95.dtb"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "ucm-imx95_defconfig,sdcard"

KERNEL_MODULE_AUTOLOAD:append = " mlan moal btnxpuart "

CL_RELEASE = "2.1"
