# Roll back to the imx-sys-mng 2026q1
PREFERRED_VERSION_imx-system-manager:compulab-mx95 = "2026q1"

# Roll back to the ele 2.0.5
PREFERRED_VERSION_firmware-ele-imx:compulab-mx95 = "2.0.5"

# Roll back to the optee-os 4.8.0.imx
PREFERRED_VERSION_optee-os:compulab-mx95 = "4.8.0.imx"
PREFERRED_VERSION_optee-client:compulab-mx95 = "4.8.0.imx"
PREFERRED_VERSION_optee-test:compulab-mx95 = "4.8.0.imx"

# Roll back to the u-boot 2025.04
PREFERRED_VERSION_u-boot-compulab:compulab-mx95 = "2025.04"
# MACHINEOVERRIDES =. "uboot_2025:"
